# Host to use for canonical URL generation (without trailing slash)
host: 

# Header-related options
show_govuk_logo: true
service_name: Wallet
service_link: https://www.gov.uk/wallet
phase: Beta

# Links to show on right-hand-side of header
header_links:
  GOV.UK Wallet: /
  Issue credentials: /issue-credentials/issue-credentials/
  Verify credentials: /verify-credentials /verify-credentials/

  # Links to show in the page footer
footer_links:
  Accessibility: /accessibility-statement.html

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: true

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:

# Enable multipage navigation in the sidebar
multipage_nav: true

# Enable collapsible navigation in the sidebar
collapsible_nav: true

# Table of contents depth â€“ how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 2

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false

show_contribution_banner: false
github_repo: govuk-one-login/mobile-wallet-tech-docs
github_branch: main

redirects:
  /issue-credentials/index.html: /issue-credentials/issue-credentials/
  /verify-credentials/index.html: /verify-credentials/verify-credentials/

# API description
api_path: ./openapi/cri.yaml
