name: Check Pull Request

on:
  pull_request:

jobs:
  check-conventional-commits:
    name: Check conventional commits
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          # Pick the PR HEAD instead of the merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Verify conventional commit standards
        uses: cocogitto/cocogitto-action@9a9fe03b31c47444290c0d7f9b1ee1b44ee13f20 # v4.1.0
        with:
          command: check
          args: --from-latest-tag

  check-pull-request:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: Setup Ruby
        uses: ruby/setup-ruby@d5126b9b3579e429dd52e51e68624dda2e05be25 # v1.267.0
        with:
          bundler-cache: true
      - name: Build Middleman
        run: bundle exec middleman build --verbose